// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
)

const getPayment = `-- name: GetPayment :one
SELECT id, request_id FROM payment
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(&i.ID, &i.RequestID)
	return i, err
}
