// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreateWager(ctx context.Context, in *CreateWagerRequest, opts ...grpc.CallOption) (*CreateWagerResponse, error)
	BuyWager(ctx context.Context, in *BuyWagerRequest, opts ...grpc.CallOption) (*BuyWagerResponse, error)
	GetWager(ctx context.Context, in *GetWagerRequest, opts ...grpc.CallOption) (*GetWagerResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateWager(ctx context.Context, in *CreateWagerRequest, opts ...grpc.CallOption) (*CreateWagerResponse, error) {
	out := new(CreateWagerResponse)
	err := c.cc.Invoke(ctx, "/v1.PaymentService/CreateWager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) BuyWager(ctx context.Context, in *BuyWagerRequest, opts ...grpc.CallOption) (*BuyWagerResponse, error) {
	out := new(BuyWagerResponse)
	err := c.cc.Invoke(ctx, "/v1.PaymentService/BuyWager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetWager(ctx context.Context, in *GetWagerRequest, opts ...grpc.CallOption) (*GetWagerResponse, error) {
	out := new(GetWagerResponse)
	err := c.cc.Invoke(ctx, "/v1.PaymentService/GetWager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility
type PaymentServiceServer interface {
	CreateWager(context.Context, *CreateWagerRequest) (*CreateWagerResponse, error)
	BuyWager(context.Context, *BuyWagerRequest) (*BuyWagerResponse, error)
	GetWager(context.Context, *GetWagerRequest) (*GetWagerResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (UnimplementedPaymentServiceServer) CreateWager(context.Context, *CreateWagerRequest) (*CreateWagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWager not implemented")
}
func (UnimplementedPaymentServiceServer) BuyWager(context.Context, *BuyWagerRequest) (*BuyWagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyWager not implemented")
}
func (UnimplementedPaymentServiceServer) GetWager(context.Context, *GetWagerRequest) (*GetWagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWager not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreateWager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateWager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PaymentService/CreateWager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateWager(ctx, req.(*CreateWagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_BuyWager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyWagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).BuyWager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PaymentService/BuyWager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).BuyWager(ctx, req.(*BuyWagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetWager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetWager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PaymentService/GetWager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetWager(ctx, req.(*GetWagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWager",
			Handler:    _PaymentService_CreateWager_Handler,
		},
		{
			MethodName: "BuyWager",
			Handler:    _PaymentService_BuyWager_Handler,
		},
		{
			MethodName: "GetWager",
			Handler:    _PaymentService_GetWager_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
